config/routes.rb
Rails.application.routes.draw do
  get '/index' =>'posts#index'
  get '/top' => 'home#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/posts' =>'posts#create'
  get '/posts/:id' => 'posts#show', as: 'post'
  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
  	post = Post.new(post_params)
  	post.save
  	redirect_to'/index'
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  	@post = Post.find(params[:id])
  end
  def update
  	post = Post.find(params[:id])
        post.update(post_params)
        redirect_to post_path(post.id)
  end
  def destroy
  	post = Post.find(params[:id])
  	post.destroy
  	redirect_to index_path
  end


  private
  def post_params
  	params.require(:post).permit(:title,:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/top.html.erb
<h1>ようこそBookersへ！</h1>
<p><span>Bookers</span>では、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換する事ができます
</p>
<%= link_to"Start", "/index"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>
    <h4>title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <br><%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", post_path(@post.id) %>
<%= link_to "Back", index_path %>

app/views/posts/index.html.erb
 <h1>Books</h1>
 <table class="table">
<tr class="title">
 	<th><h3>Title</h3></th>
 	<th><h3>Body</h3></th>
</tr>
 <% @posts.each do |post| %>
    <tr class="body">
    	<td><%= post.title %></td>
    	<td><%= post.body %></td>
    	<td><%= link_to "Show", post_path(post.id)%></td>
    	<td><%= link_to "Edit", edit_post_path(post.id)%></td>
    	<td><%= link_to "Destroy", destroy_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    </tr>
 <% end %>
</table>

 <h1>New book</h1>
<%= form_for(@post) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <br><%= f.submit 'Create Book' %>

<% end %>

app/views/posts/show.html.erb
<h2>Title</h2>
<p><%= @post.title %></p>
<h2>Body</h2>
<p><%= @post.body %></p>
<%= link_to "Edit", edit_post_path(@post.id) %>
<%= link_to "Back", index_path %>